name: Build Executable

on:
  push:
    tags:
      - 'v*' # Executar quando tags de versão forem criadas
  workflow_dispatch: # Permitir execução manual

jobs:
  build:
    runs-on: windows-latest # Precisamos de Windows para criar .exe

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name=xml-processor-windows --distpath=dist run.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: xml-processor-windows
        path: dist/xml-processor-windows.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/xml-processor-windows.exe